server:
  port: ${SERVER_PORT}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: ${SHOW_SQL}
  application:
    name: bot
telegram:
  referral: ${TG_REFERRAL}
  free_channel: ${TG_FREE_CHANNEL_LINK}
  bot:
    token: ${BOT_TOKEN}
    username: ${BOT_USERNAME}
chat:
  chat-id: ${CHAT_ID}
  public-chat-id: ${PUBLIC_CHAT_ID}

trybit:
  secret-key: ${TRY_BIT_SECRET}
  api-token: ${TRY_BIT_API_TOKEN}
  shop-id: ${TRY_BIT_SHOP_ID}

subscription:
  reminder-days-before: ${REMINDER_DAYS_BEFORE}
  cron:
    check-expired: ${CHECK_EXPIRED}
    reminder: ${REMINDER}